config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show], param: :username
  resources :rewards
  resources :admin, except: [:edit ]

  root to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard/', to: 'sessions#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    current_user ||= User.new
    can :read, User, id: current_user.id
    can :read, Reward, id: current_user.id

    if current_user.admin?
      can :manage, :all
    end
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  validates :name, :point_value, presence:true
  validates_numericality_of :point_value, on: :create

  has_many :user_rewards
  has_many :users, through: :user_rewards
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence:true
  has_secure_password
  has_many :user_rewards
  has_many :rewards, through: :user_rewards

  enum role: %w(default admin)

  def to_param
    username
  end

end

app/models/user_reward.rb
class UserReward < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    if current_user.admin?
      authorize! :manage, @current_user
      @users = User.all
    else
      flash[:error] = "You are not authorized to see this page."
      redirect_to root_url
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.available_points += (params[:admin][:available_points]).to_i
    user.redeem_points += (params[:admin][:redeem_points]).to_i
    user.save
    flash[:changed] = "Changes Made"
    redirect_to admin_path
  end

  def destroy
    user = User.find(params[:id])
    user.available_points = 0
    user.redeemed_points = 0
    user.save
    redirect_to admin_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    if current_user
      authorize! :read, @current_user
      @rewards = Reward.all
    else
      flash[:error] = "You must sign in to see this information."
      redirect_to root_url
    end
  end

  def new
  end

  def create
    reward = Reward.new(name: params[:reward][:name], point_value: params[:reward][:point_value])
    if reward.save
      redirect_to rewards_path
    else
      flash[:error] = "Please fill in all of the fields. Make sure your point value is a number"
      render :new
    end
  end

  def update
    user = User.find(params[:id])
    reward = Reward.find_by(id: params[:admin][:reward])
    if reward.point_value > user.available_points
      flash[:cheap] = "You don't have enough points to claim that reward."
    else
      user.available_points -= reward.point_value
      user.redeem_points += reward.point_value
      user.rewards << reward
      user.save
    end
    redirect_to rewards_path
  end

  def edit

  end

  def destroy
    reward = Reward.find(params[:id])
    reward.destroy
    redirect_to rewards_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    if current_user
      authorize! :read, @current_user
      @available = current_user.available_points
      @redeemed = current_user.redeem_points
      @redeemed_rewards = current_user.rewards
    else
      flash[:error] = "You must sign in to see this information."
      redirect_to root_url
    end
  end

  def new
  end

  def create

    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = "Invalid login."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Successfully logged out."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @user = User.find_by(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :password,
                                 :password_confirmation)
  end

   def authorize
     if current_user.nil?
       redirect_to login_path, alert: "You are not authorized to access this page"
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>All Users</h1>
<div class="row">

    <% @users.each do |user| %>
    <div class="users col-md-3">
    <p>Name: <%= user.username%></p>
    <p>Available Points: <%= user.available_points %></p>
    <p>Redeemed Points: <%= user.redeem_points %></p>
    <p>Rewards Received:
      <% user.rewards.each do |reward|  %>
        <p>
        <%= reward.name %>
        </p>
      <% end %></p>
      <%= link_to "Edit Points", admin_path(user.id) %>
    </div>
    <% end %>
</div>

app/views/admin/show.html.erb
<h1>Change <%= @user.username %>'s Points </h1>

<p>
  Current Available Points:
  <%= @user.available_points %>
</p>

<%= form_for(:admin, url: admin_path, method: :patch) do |f| %>
  <% f.hidden_field :user_id, :value => @user.id %>
<p>
  <%= f.label 'Update Available Points:' %>
  <%= f.text_field :available_points %>
</p>
<p>
  Current Redeemed Points:
  <%= @user.redeem_points %>
</p>

<p>
  <%= f.label 'Redeemed Points:' %>
  <%= f.text_field :redeem_points %>
</p>
<%= f.submit "Update Points" %>
<% end %>


<%= form_for(:admin, url: admin_path, method: :delete) do |f| %>
<% f.hidden_field :user_id, :value => @user.id %>
<%= f.submit "Delete User's Points" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'custom' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/dashboard">PointBox</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <% if current_user.admin?%>
            <li><%= link_to "Admin", admin_index_path %></li>
            <% end %>
          <li><%= link_to "Your Dashboard", dashboard_path %></li>
          <li><%= link_to "Rewards", rewards_path %></li>
          <% end %>

          <% if logged_in? %>
          <p class="navbar-text">Signed in as <%= current_user.username %></p>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <div class="container">


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</div>
</body>
</html>

app/views/rewards/_form.html.erb
<%= form_for(:reward, url: rewards_path, method: :post) do |f| %>
<p><%= f.label 'Description: ' %>
<%= f.text_field :name %></p>
<p><%= f.label 'Point Value: ' %>
<%= f.text_field :point_value %></p>
<%= f.submit %>
<% end %>

app/views/rewards/edit.html.erb
<h1>Edit the Reward</h1>

<%= render 'form' %>

app/views/rewards/index.html.erb
<h1>Rewards</h1>

<h3>You have <%= current_user.available_points %> points available for use.</h3>
  <div class="row">
    <% @rewards.each do |reward| %>
      <div class="rewards col-md-3">
        <p><%= reward.name %></p>
        <p>Point Value: <%= reward.point_value %></p>


        <%= form_for(:admin, url: reward_path(current_user.id), method: :put) do |f| %>
        <%= f.hidden_field :reward, value: reward.id %>
        <%= f.submit "Choose This Reward" %>
        <% end %>

        <% if current_user.admin? %>
        <br>
        <p><%= link_to "Edit this Reward", edit_reward_path(current_user.id) %></p>
        <p><%= link_to "Delete this Reward", reward_path(reward), method: :delete %></p>
        <% end %>

      </div>
    <% end  %>
  <div class="reward-button col-md-12">
    <p>
      <% if current_user.admin? %>
        <%= link_to "Create a New Reward", new_reward_path %>
      <% end %>
    </p>
  </div>
  </div>
</table>

app/views/rewards/new.html.erb
<h1>Create a New Reward</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <p><%= f.label :username %></p>
  <p><%= f.text_field :username %></p>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Create Account" %></p>
<% end  %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>
<p>Available Points: <%= @user.available_points %></p>
<p>Redeemed Points: <%= @user.redeem_points %></p>